# https://taskfile.dev

version: '3'

vars:
  DCR: ${DCR}
  VERSION: "1.0"

tasks:
  build:
    desc: build the token server
    cmds:
      - |
        docker build \
        -t {{.DCR}}livekit-token-server:{{.VERSION}} \
        .

  run:
    desc: run the token server
    cmds:
      - |
        docker run -d \
        --rm \
        -e API_KEY=my-key \
        -e API_SECRET=my-secret \
        -p 3030:3030 \
        --name livekit-token-server \
        {{.DCR}}livekit-token-server:{{.VERSION}}